### ISSUE TITLE
Is method .printList() Missing?

### ISSUE THREAD

**Issue by BlakesEyeR1** [jasonsjones/doubly-linked-list#17]
Is method .printList() Missing?

**Comment by jasonsjones** [comment]
Hey @BlakesEyeR1, thanks for the question and sincerely apologize for the _very_ delayed response 😞 .

Yes, looks like it is missing and might have been another copy/paste doc mistake that I've been known for 😄 .  I'll update the docs until the `printList()` method is implemented, which I'll add to the list when I include the repo in my [data-structures](https://github.com/jasonsjones/data-structures) monorepo (wip at the moment)

But...feel free to open a PR in the meantime if you need it sooner than later and I'll be more than happy to take a look. 👍
